on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        name:
          [
            debian,
            ubuntu,
            docker,
            app,
            caddy,
            devpi,
            logstash,
            n2n,
            coredns,
            isc-dhcpd,
            mysql,
            tomcat,
          ]

    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ matrix.name }}
          package-type: "container"
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"
