name: "Build DevContainers"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/devcontainers.yml"
      - "devcontainers/**"
  # Triggered every week.
  schedule:
    - cron: "0 0 * * FRI"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    strategy:
      matrix:
        devcontainer: [prebuilder, debian]

    steps:
      - uses: actions/checkout@v5

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/${{ matrix.devcontainer }}
          imageName: ${{ env.REGISTRY }}/${{ github.repository_owner }}/devcontainer
          imageTag: ${{ matrix.devcontainer }}
          cacheFrom: ${{ env.REGISTRY }}/${{ github.repository_owner }}/devcontainer:${{ matrix.devcontainer }}
          push: always
